version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Monter votre projet local dans le container
      - /app/node_modules # Monter le dossier node_modules pour éviter les conflits locaux
      - ./prisma:/app/prisma  # Monter le dossier prisma contenant dev.db
    ports:
      - "3000:3000" # Rediriger le port 3000 pour l'accès local
    environment:
      - DATABASE_URL=file:./prisma/dev.db # URL de la base de données SQLite
    restart: always # Redémarrer le container en cas d'échec

volumes:
  node_modules:
